name: Run Full Test Suite and Publish Allure Report

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".docker/docker-compose.yaml"

      - name: Wait for services to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Run All Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Full Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          destination_dir: all-reports/run-${{ github.run_id }}

      - name: Deploy static index.html to GitHub Pages root
        run: |
          mkdir -p site-root
          cat > site-root/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Allure Reports Dashboard</title>
            <style>
              body { font-family: sans-serif; padding: 2rem; background: #f9f9f9; }
              h1 { font-size: 2rem; margin-bottom: 1rem; }
              h2 { margin-top: 2rem; }
              ul { list-style: none; padding: 0; }
              li { margin: 0.5rem 0; }
              a { color: #0366d6; text-decoration: none; }
              .tag { font-size: 0.8rem; background: #eee; padding: 0.2rem 0.4rem; border-radius: 4px; margin-left: 0.5rem; }
              .footer { margin-top: 2rem; color: #777; font-size: 0.9rem; }
            </style>
          </head>
          <body>
            <h1>🧪 Allure Reports Dashboard</h1>
            <h2>📘 Full Test Suite Reports</h2>
            <ul id="full-reports">Loading...</ul>
            <h2>🎯 Single Test Reports</h2>
            <ul id="single-reports">Loading...</ul>
            <div class="footer">Auto-generated with ❤️ using GitHub Pages + JS</div>
            <script>
              async function loadReports(basePath, targetId) {
                const listEl = document.getElementById(targetId);
                try {
                  const res = await fetch(`${basePath}`);
                  const html = await res.text();
                  const matches = Array.from(html.matchAll(/href=\"([^\"]+)\//g));
                  const folders = [...new Set(matches.map(m => m[1]))].filter(n => n.startsWith('run-') || !n.includes('.'));
                  if (folders.length === 0) {
                    listEl.innerHTML = '<li>No reports found.</li>';
                    return;
                  }
                  listEl.innerHTML = '';
                  folders.forEach(name => {
                    const li = document.createElement('li');
                    li.innerHTML = `<a href="${basePath}${name}/index.html" target="_blank">${name}</a> <span class="tag">${name}</span>`;
                    listEl.appendChild(li);
                  });
                } catch (e) {
                  listEl.innerHTML = '<li>Error loading reports</li>';
                  console.error(e);
                }
              }
              loadReports('all-reports/', 'full-reports');
              loadReports('single-test-reports/', 'single-reports');
            </script>
          </body>
          </html>
          EOF

      - name: Deploy index.html to GitHub Pages root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site-root
          destination_dir: .