name: Run Single Test and Publish Allure Report

on:
  workflow_dispatch:
    inputs:
      testName:
        description: 'Test class name'
        required: true
        default: 'EmptyLoginTest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ".docker/docker-compose.yaml"

      - name: Wait for services to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      - name: Run Selected Test
        run: mvn clean verify -Dtest=${{ github.event.inputs.testName }}

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Clone existing gh-pages content
        run: |
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages-content

      - name: Deploy Single Test Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          destination_dir: single-test-reports/${{ github.event.inputs.testName }}-${{ github.run_id }}

      - name: Generate dynamic index.html
        run: |
          mkdir -p site-root
          cat > site-root/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Allure Reports Dashboard</title>
            <style>
              body { font-family: "Segoe UI", sans-serif; background: #f4f6f8; color: #333; margin: 0; padding: 2rem; }
              .container { max-width: 800px; margin: auto; }
              h1 { font-size: 2rem; color: #2c3e50; }
              h2 { margin-top: 2rem; }
              ul { list-style: none; padding-left: 0; }
              li { margin: 0.5rem 0; }
              a { color: #007acc; text-decoration: none; }
              a:hover { color: #005a99; }
              .tag { background: #e3f2fd; color: #0d47a1; font-size: 0.8rem; padding: 0.2rem 0.5rem; border-radius: 4px; margin-left: 0.5rem; }
              .footer { margin-top: 3rem; font-size: 0.9rem; color: #888; }
            </style>
          </head>
          <body><div class="container">
            <h1>🧪 Allure Reports Dashboard</h1>
            <h2>📘 Full Test Suite Reports</h2><ul>
          EOF

          for d in gh-pages-content/all-reports/run-*; do
            name=$(basename "$d")
            echo "<li><a href=\"all-reports/$name/index.html\" target=\"_blank\">$name</a> <span class=\"tag\">$name</span></li>" >> site-root/index.html
          done

          echo "</ul><h2>🎯 Single Test Reports</h2><ul>" >> site-root/index.html

          for d in gh-pages-content/single-test-reports/*; do
            name=$(basename "$d")
            echo "<li><a href=\"single-test-reports/$name/index.html\" target=\"_blank\">$name</a> <span class=\"tag\">$name</span></li>" >> site-root/index.html
          done

          cat >> site-root/index.html <<'EOF'
            </ul><div class="footer">Deployed with ❤️ by GitHub Actions</div></div></body></html>
          EOF

      - name: Deploy index.html to GitHub Pages root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site-root
          destination_dir: .